//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HePa.Resource.Display {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HePa.Resource.Display.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh đại diện.
        /// </summary>
        public static string DisplayAvatar {
            get {
                return ResourceManager.GetString("DisplayAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string DisplayBirthDay {
            get {
                return ResourceManager.GetString("DisplayBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/Thành phố.
        /// </summary>
        public static string DisplayCity {
            get {
                return ResourceManager.GetString("DisplayCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string DisplayConfirmPassword {
            get {
                return ResourceManager.GetString("DisplayConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string DisplayDay {
            get {
                return ResourceManager.GetString("DisplayDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị.
        /// </summary>
        public static string DisplayDisplayName {
            get {
                return ResourceManager.GetString("DisplayDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố/Quận/Huyện.
        /// </summary>
        public static string DisplayDistrict {
            get {
                return ResourceManager.GetString("DisplayDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string DisplayEmailAddress {
            get {
                return ResourceManager.GetString("DisplayEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề nghiệp.
        /// </summary>
        public static string DisplayJob {
            get {
                return ResourceManager.GetString("DisplayJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string DisplayMonth {
            get {
                return ResourceManager.GetString("DisplayMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string DisplayPassword {
            get {
                return ResourceManager.GetString("DisplayPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string DisplayPhoneNumber {
            get {
                return ResourceManager.GetString("DisplayPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi ở.
        /// </summary>
        public static string DisplayPlace {
            get {
                return ResourceManager.GetString("DisplayPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xã/Phường/Thị trấn.
        /// </summary>
        public static string DisplayTown {
            get {
                return ResourceManager.GetString("DisplayTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string DisplayYear {
            get {
                return ResourceManager.GetString("DisplayYear", resourceCulture);
            }
        }
    }
}
