//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HePa.Resource.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_word_vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_word_vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HePa.Resource.Page.Resource.word_vi", typeof(Resource_word_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ.
        /// </summary>
        public static string ButtonCancelComment {
            get {
                return ResourceManager.GetString("ButtonCancelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string ButtonCloseLession {
            get {
                return ResourceManager.GetString("ButtonCloseLession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string ButtonSendComment {
            get {
                return ResourceManager.GetString("ButtonSendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình luận bài này với những người học khác.
        /// </summary>
        public static string PlaceHderComment {
            get {
                return ResourceManager.GetString("PlaceHderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ôn lại.
        /// </summary>
        public static string TabReview {
            get {
                return ResourceManager.GetString("TabReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay.
        /// </summary>
        public static string TabToday {
            get {
                return ResourceManager.GetString("TabToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bình luận.
        /// </summary>
        public static string TextCommentCount {
            get {
                return ResourceManager.GetString("TextCommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục tiêu hàng ngày.
        /// </summary>
        public static string TextDailyGoal {
            get {
                return ResourceManager.GetString("TextDailyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau quá trình học bạn có thể đặt một câu với từ vừa học để luyện tập và mọi người có thể bình luận thêm câu của bạn..
        /// </summary>
        public static string TextDiscussGuide {
            get {
                return ResourceManager.GetString("TextDiscussGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        public static string TextLearnedWord {
            get {
                return ResourceManager.GetString("TextLearnedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách từ hôm nay.
        /// </summary>
        public static string TextTodayWordList {
            get {
                return ResourceManager.GetString("TextTodayWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghe phát âm giọng Anh Mỹ (NAmE).
        /// </summary>
        public static string TooltipAudio {
            get {
                return ResourceManager.GetString("TooltipAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mục tiêu hàng ngày.
        /// </summary>
        public static string TooltipChangeDailyGoal {
            get {
                return ResourceManager.GetString("TooltipChangeDailyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví dụ.
        /// </summary>
        public static string TooltipExample {
            get {
                return ResourceManager.GetString("TooltipExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên âm quốc tế (NAmE).
        /// </summary>
        public static string TooltipIPA {
            get {
                return ResourceManager.GetString("TooltipIPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghĩa của từ.
        /// </summary>
        public static string TooltipMeaning {
            get {
                return ResourceManager.GetString("TooltipMeaning", resourceCulture);
            }
        }
    }
}
